// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFzq-NdOXaQN8b4wb7easl9y6suGxFmwk',
    appId: '1:659818678756:web:75c098dcf5ecf0c5fe1ff1',
    messagingSenderId: '659818678756',
    projectId: 'todo-list-74a5f',
    authDomain: 'todo-list-74a5f.firebaseapp.com',
    storageBucket: 'todo-list-74a5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVxlV7LU50fIdfn6c6bC9zBBxfWnwGZUA',
    appId: '1:659818678756:android:66141295b2c81d85fe1ff1',
    messagingSenderId: '659818678756',
    projectId: 'todo-list-74a5f',
    storageBucket: 'todo-list-74a5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOe58ExA_ALNt61oC9jPFr_5Y0pmEkgRg',
    appId: '1:659818678756:ios:03da656faf619495fe1ff1',
    messagingSenderId: '659818678756',
    projectId: 'todo-list-74a5f',
    storageBucket: 'todo-list-74a5f.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOe58ExA_ALNt61oC9jPFr_5Y0pmEkgRg',
    appId: '1:659818678756:ios:f0e085707a6358f5fe1ff1',
    messagingSenderId: '659818678756',
    projectId: 'todo-list-74a5f',
    storageBucket: 'todo-list-74a5f.appspot.com',
    iosBundleId: 'com.example.todoList.RunnerTests',
  );
}
